name: swarmui_flutter
description: "A Flutter client for SwarmUI"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  provider: ^6.0.0
  shared_preferences: ^2.0.6
  web_socket_channel: ^2.1.0
  image_picker: ^0.8.5+4
  logger: ^1.3.0
  dropdown_search: ^5.0.3
  # path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
